apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopparserapi-deployment
spec:
  selector:
    matchLabels:
      app: shopparserapi-pod
  template:
    metadata:
      labels:
        app: shopparserapi-pod
    spec:
      containers:
        - name: shopparserapi-constainer
          image: argiziont/shopparserapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      # restartPolicy: Always