apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopparserclientapp-deployment
spec:
  selector:
    matchLabels:
      app: shopparserclientapp-pod
  template:
    metadata:
      labels:
        app: shopparserclientapp-pod
    spec:
      containers:
        - name: shopparserclientapp-constainer
          image: argiziont/shopparserclientapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      # restartPolicy: Always